services:
  qqmonitor_api:
    image: qqmonitor_api
    build: .
    depends_on:
      - qqmonitor_database
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PORT: ${PORT}
      SERVICE_PATH: ${SERVICE_PATH}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
    command: ["node", "src/main.js"]


  qqmonitor_database:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  pgdata:
